import '@/styles/globals.css';

import { GeistSans } from 'geist/font/sans';
import { type Metadata } from 'next';
import { SessionProvider } from 'next-auth/react';
import { TRPCReactProvider } from '@/trpc/react';
import { AntdRegistry } from '@ant-design/nextjs-registry';
import { ConfigProvider } from 'antd';
import darkTheme from '@/theme/darkTheme';
import defaultTheme from '@/theme/themeConfig';
import Layout from '@/app/dashboard/components/layout';

export const metadata: Metadata = {
  title: 'Create T3 App',
  description: 'Generated by create-t3-app',
  icons: [{ rel: 'icon', url: '/favicon.ico' }],
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const isDarkMode = true;
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body>
        <SessionProvider>
          <TRPCReactProvider>
            <AntdRegistry>
              <ConfigProvider theme={isDarkMode ? darkTheme : defaultTheme}>
                {/* {children} */}
                <Layout/>
              </ConfigProvider>
            </AntdRegistry>
          </TRPCReactProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
